# Generated by Django 2.2.12 on 2020-04-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200425_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_assignment',
            name='module_video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testVideo', to='courses.Grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file', 'module_assignment', 'announcement')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
