# Generated by Django 2.2.12 on 2020-04-25 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200425_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
