# Generated by Django 2.2.12 on 2020-04-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignment_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module_assignment',
            name='module_assignment',
        ),
        migrations.RemoveField(
            model_name='module_assignment',
            name='module_video',
        ),
        migrations.AddField(
            model_name='module_assignment',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
