# Generated by Django 2.2.12 on 2020-04-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200425_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module_assignment',
            name='text',
        ),
        migrations.AddField(
            model_name='module_assignment',
            name='assign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_link', to='courses.Assignment'),
            preserve_default=False,
        ),
    ]
