# Generated by Django 2.2.12 on 2020-04-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200425_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='start_date',
        ),
    ]
